services:
  frontend:
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - 4000:4000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`staging.linkbook.store`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=le"
      - "traefik.http.routers.frontend.tls.domains[0].main=staging.linkbook.store"
      - "traefik.http.middlewares.frontend-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.frontend.middlewares=frontend-redirect"
    networks:
      - traefikNetwork
    volumes:
      - "~/shared_vps/traefik/certs:/letsencrypt"
networks:
  traefikNetwork:
    external: true
